version: '3.9'
services:

  database:
    container_name: database
    image: postgres:13
    env_file:
      - env.database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django -d django"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: on-failure:3
    networks:
      - backend

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    image: frontend:latest
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: on-failure:3
    networks:
      - frontend
    ports:
      - 3000:3000
  
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: lib_catalog/Dockerfile.backend
    healthcheck:
      test: curl --fail http://localhost:8000/admin || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: on-failure:3
    networks:
      - frontend
      - backend
    ports:
      - 8000:8000
    
networks:
  frontend:
    driver: bridge
    ipam:
     config:
     - subnet: 192.168.100.0/24
       gateway: 192.168.100.1
  backend:
    driver: bridge
    ipam:
     config:
     - subnet: 192.168.101.0/24
       gateway: 192.168.101.1
