FROM python:3.9
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY lib_catalog/requirements.txt /app/
COPY ./lib_catalog /app/
EXPOSE 8000
RUN pip install -r requirements.txt
CMD sh init.sh && python3 manage.py runserver 0.0.0.0:8000